pipeline {
    agent {
        node {
            label 'AGENT-1'
        
    }
    }

    options {
        ansiColor('xterm')
        timeout(time: 1, unit: 'HOURS')
        disableConcurrentBuilds()
    }

    
    // build
    stages {
        stage('init') {
            steps {
                sh """
                    cd 01-vpc
                    terraform init -reconfigure
                """
            }
        }
        stage('plan') {
            steps {
                sh """
                    cd 01-vpc
                    terraform plan
                """
            }
        }
        stage('Deploy') {
            input {
                message "Should we continue?"
                ok "Yes, we should."
                // submitter "alice,bob"
                // parameters {
                //     string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
                //  }
            }
            steps {
                sh """
                    cd 01-vpc
                    terraform apply -auto-approve

                """
            }
        }    
    }    


    // after build execution post is used check the status of execution 
    post { 
        always { 
            echo 'I will always say Hello again!'
        }
        failure { 
            echo 'The jenkins script is failed'
        }
        success { 
            echo 'The jenkins script is passed successfully'
        }
        
    }
}


